locations = ['rio', 'sao paolo', 'bangkok', 'london', 'sydney', 'auckland', 'los angeles']
print(locations)
print(sorted(locations))
print(locations)
print(sorted(locations, reverse = True))
print(locations)
locations.reverse()
print(locations)
locations.sort()
print(locations)
locations.sort(reverse = True)
print(locations)
